# Autogenerated wrapper script for aws_c_auth_jll for x86_64-w64-mingw32
export libaws_c_auth

using aws_c_cal_jll
using aws_c_http_jll
using aws_c_sdkutils_jll
JLLWrappers.@generate_wrapper_header("aws_c_auth")
JLLWrappers.@declare_library_product(libaws_c_auth, "libaws-c-auth.dll")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_cal_jll, aws_c_http_jll, aws_c_sdkutils_jll)
    JLLWrappers.@init_library_product(
        libaws_c_auth,
        "bin\\libaws-c-auth.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
